### ISSUE TITLE
WorkerSystem AssociationError

### ISSUE THREAD

**Issue by anant1525** [typesafehub/activator-akka-distributed-workers-java#9]
Hi,

I am working on upgrading the akka distributed workers (in similar lines with the distributed works example), master is ClusterSingletonManager and WorkersSystem is coming up, but getting the strange Association error.

Using Akka 2.4.17 also faced the same issue with akka 2.5.4.

Please suggest, looks like we are stuck here.

2018-03-30 10:31:02,963 INFO [stdout] (WorkerSystem-akka.actor.default-dispatcher-25) [INFO] [03/30/2018 10:31:02.953] [ServerService Thread Pool -- 78] [akka.remote.Remoting] Remoting started; listening on addresses :[akka.tcp://WorkerSystem@127.0.0.1:4002]
2018-03-30 10:31:02,965 INFO [stdout] (WorkerSystem-akka.actor.default-dispatcher-30) [INFO] [03/30/2018 10:31:02.960] [ServerService Thread Pool -- 78] [akka.remote.Remoting] Remoting now listens on addresses: [akka.tcp://WorkerSystem@127.0.0.1:4002]
2018-03-30 10:31:03,046 INFO [stdout] (WorkerSystem-akka.actor.default-dispatcher-15) [INFO] [03/30/2018 10:31:03.021] [ServerService Thread Pool -- 78] [akka.remote.Remoting] Starting remoting
2018-03-30 10:31:03,083 INFO [stdout] (WorkerSystem-akka.actor.default-dispatcher-28) [INFO] [03/30/2018 10:31:03.077] [ServerService Thread Pool -- 78] [akka.remote.Remoting] Remoting started; listening on addresses :[akka.tcp://WorkerSystem@127.0.0.1:4003]
2018-03-30 10:31:03,100 INFO [stdout] (WorkerSystem-akka.actor.default-dispatcher-35) [INFO] [03/30/2018 10:31:03.077] [ServerService Thread Pool -- 78] [akka.remote.Remoting] Remoting now listens on addresses: [akka.tcp://WorkerSystem@127.0.0.1:4003]
2018-03-30 10:31:03,145 INFO [stdout] (WorkerSystem-akka.actor.default-dispatcher-14) [INFO] [03/30/2018 10:31:03.144] [ServerService Thread Pool -- 78] [akka.remote.Remoting] Starting remoting
2018-03-30 10:31:03,185 INFO [stdout] (WorkerSystem-akka.actor.default-dispatcher-27) [INFO] [03/30/2018 10:31:03.183] [ServerService Thread Pool -- 78] [akka.remote.Remoting] Remoting started; listening on addresses :[akka.tcp://WorkerSystem@127.0.0.1:4004]
2018-03-30 10:31:03,186 INFO [stdout] (WorkerSystem-akka.actor.default-dispatcher-29) [INFO] [03/30/2018 10:31:03.184] [ServerService Thread Pool -- 78] [akka.remote.Remoting] Remoting now listens on addresses: [akka.tcp://WorkerSystem@127.0.0.1:4004]
2018-03-30 10:31:03,231 INFO [stdout] (WorkerSystem-akka.actor.default-dispatcher-10) [INFO] [03/30/2018 10:31:03.230] [ServerService Thread Pool -- 78] [akka.remote.Remoting] Starting remoting
2018-03-30 10:31:03,259 INFO [stdout] (WorkerSystem-akka.actor.default-dispatcher-24) [INFO] [03/30/2018 10:31:03.255] [ServerService Thread Pool -- 78] [akka.remote.Remoting] Remoting started; listening on addresses :[akka.tcp://WorkerSystem@127.0.0.1:4005]
2018-03-30 10:31:03,261 INFO [stdout] (WorkerSystem-akka.actor.default-dispatcher-28) [INFO] [03/30/2018 10:31:03.256] [ServerService Thread Pool -- 78] [akka.remote.Remoting] Remoting now listens on addresses: [akka.tcp://WorkerSystem@127.0.0.1:4005]
2018-03-30 10:31:03,325 INFO [stdout] (WorkerSystem-akka.actor.default-dispatcher-13) [INFO] [03/30/2018 10:31:03.324] [ServerService Thread Pool -- 78] [akka.remote.Remoting] Starting remoting
**2018-03-30 10:31:03,331 INFO [stdout] (WorkerSystem-akka.actor.default-dispatcher-5) [ERROR] [03/30/2018 10:31:03.330] [WorkerSystem-akka.remote.default-remote-dispatcher-22] [akka.tcp://WorkerSystem@127.0.0.1:4002/system/endpointManager/reliableEndpointWriter-akka.tcp%3A%2F%2FClusterSystem%40127.0.0.1%3A2551-0/endpointWriter] AssociationError [akka.tcp://WorkerSystem@127.0.0.1:4002] -> [akka.tcp://ClusterSystem@127.0.0.1:2551]: Error [[B cannot be cast to [C] [
2018-03-30 10:31:03,331 INFO [stdout] (WorkerSystem-akka.actor.default-dispatcher-5) java.lang.ClassCastException: [B cannot be cast to [C
2018-03-30 10:31:03,332 INFO [stdout] (WorkerSystem-akka.actor.default-dispatcher-5) at deployment.jaxrpc.war//akka.remote.artery.FastHash$.ofString(LruBoundedCache.scala:18)**
2018-03-30 10:31:03,332 INFO [stdout] (WorkerSystem-akka.actor.default-dispatcher-5) at deployment.jaxrpc.war//akka.remote.serialization.ActorRefResolveCache.hash(ActorRefResolveCache.scala:61)
2018-03-30 10:31:03,332 INFO [stdout] (WorkerSystem-akka.actor.default-dispatcher-5) at deployment.jaxrpc.war//akka.remote.serialization.ActorRefResolveCache.hash(ActorRefResolveCache.scala:55)

**Comment by ktoso** [comment]
When exactly are you getting this and why in a .war?

**Comment by anant1525** [comment]
we have enclosed the code in to Spring Framework, created war deployed it on willdfly 11

**Comment by ktoso** [comment]
That's fine but does not help diagnose the issue too much; Is there a reproducer you could share?

**Comment by anant1525** [comment]
Tried the same with the sample code upgraded the code to akka 2.5.9 and getting the ask timeout here.

Since the Flow is almost similar so trying from all fronts.

[INFO] [04/02/2018 22:23:53.415] [main] [akka.remote.Remoting] Starting remoting
[INFO] [04/02/2018 22:23:53.764] [main] [akka.remote.Remoting] Remoting started; listening on addresses :[akka.tcp://ClusterSystem@127.0.0.1:2551]
[INFO] [04/02/2018 22:23:53.766] [main] [akka.remote.Remoting] Remoting now listens on addresses: [akka.tcp://ClusterSystem@127.0.0.1:2551]
[INFO] [04/02/2018 22:23:53.811] [main] [akka.cluster.Cluster(akka://ClusterSystem)] Cluster Node [akka.tcp://ClusterSystem@127.0.0.1:2551] - Starting up...
[INFO] [04/02/2018 22:23:53.959] [main] [akka.cluster.Cluster(akka://ClusterSystem)] Cluster Node [akka.tcp://ClusterSystem@127.0.0.1:2551] - Registered cluster JMX MBean [akka:type=Cluster]
[INFO] [04/02/2018 22:23:53.959] [main] [akka.cluster.Cluster(akka://ClusterSystem)] Cluster Node [akka.tcp://ClusterSystem@127.0.0.1:2551] - Started up successfully
[WARN] [04/02/2018 22:23:54.048] [ClusterSystem-akka.actor.default-dispatcher-4] [akka.tcp://ClusterSystem@127.0.0.1:2551/system/cluster/core/daemon/downingProvider] Don't use auto-down feature of Akka Cluster in production. See 'Auto-downing (DO NOT USE)' section of Akka Cluster documentation.
reached here 1
[INFO] [04/02/2018 22:23:54.157] [ClusterSystem-akka.actor.default-dispatcher-17] [akka.cluster.Cluster(akka://ClusterSystem)] Cluster Node [akka.tcp://ClusterSystem@127.0.0.1:2551] - Node [akka.tcp://ClusterSystem@127.0.0.1:2551] is JOINING, roles [backend, dc-default]
reached here 2
[INFO] [04/02/2018 22:23:54.173] [ClusterSystem-akka.actor.default-dispatcher-17] [akka.cluster.Cluster(akka://ClusterSystem)] Cluster Node [akka.tcp://ClusterSystem@127.0.0.1:2551] - Leader is moving node [akka.tcp://ClusterSystem@127.0.0.1:2551] to [Up]
[INFO] [04/02/2018 22:23:54.304] [ClusterSystem-akka.actor.default-dispatcher-4] [akka.tcp://ClusterSystem@127.0.0.1:2551/user/master] Singleton manager starting singleton actor [akka://ClusterSystem/user/master/singleton]
[INFO] [04/02/2018 22:23:54.306] [ClusterSystem-akka.actor.default-dispatcher-4] [akka.tcp://ClusterSystem@127.0.0.1:2551/user/master] ClusterSingletonManager state change [Start -> Oldest]
Apr 02, 2018 10:23:54 PM com.zaxxer.hikari.HikariDataSource <init>
INFO: slick.db - Started.
Apr 02, 2018 10:23:54 PM com.zaxxer.hikari.HikariDataSource <init>
INFO: slick.db - Started.
[WARN] [SECURITY][04/02/2018 22:23:56.352] [ClusterSystem-akka.persistence.dispatchers.default-plugin-dispatcher-23] [akka.serialization.Serialization(akka://ClusterSystem)] Using the default Java serializer for class [worker.Evt] which is not recommended because of performance implications. Use another serializer or disable this warning using the setting 'akka.actor.warn-about-java-serializer-usage'
[INFO] [04/02/2018 22:23:59.290] [main] [akka.remote.Remoting] Starting remoting
[INFO] [04/02/2018 22:23:59.373] [main] [akka.remote.Remoting] Remoting started; listening on addresses :[akka.tcp://ClusterSystem@127.0.0.1:2552]
[INFO] [04/02/2018 22:23:59.374] [main] [akka.remote.Remoting] Remoting now listens on addresses: [akka.tcp://ClusterSystem@127.0.0.1:2552]
[INFO] [04/02/2018 22:23:59.375] [main] [akka.cluster.Cluster(akka://ClusterSystem)] Cluster Node [akka.tcp://ClusterSystem@127.0.0.1:2552] - Starting up...
[WARN] [04/02/2018 22:23:59.381] [main] [akka.cluster.Cluster(akka://ClusterSystem)] Could not register Cluster JMX MBean with name=akka:type=Cluster as it is already registered. If you are running multiple clusters in the same JVM, set 'akka.cluster.jmx.multi-mbeans-in-same-jvm = on' in config
[INFO] [04/02/2018 22:23:59.381] [main] [akka.cluster.Cluster(akka://ClusterSystem)] Cluster Node [akka.tcp://ClusterSystem@127.0.0.1:2552] - Started up successfully
reached here 1
[WARN] [04/02/2018 22:23:59.386] [ClusterSystem-akka.actor.default-dispatcher-18] [akka.tcp://ClusterSystem@127.0.0.1:2552/system/cluster/core/daemon/downingProvider] Don't use auto-down feature of Akka Cluster in production. See 'Auto-downing (DO NOT USE)' section of Akka Cluster documentation.
reached here 2
[INFO] [04/02/2018 22:23:59.498] [main] [akka.remote.Remoting] Starting remoting
[INFO] [04/02/2018 22:23:59.569] [main] [akka.remote.Remoting] Remoting started; listening on addresses :[akka.tcp://WorkerSystem@127.0.0.1:54705]
[INFO] [04/02/2018 22:23:59.569] [main] [akka.remote.Remoting] Remoting now listens on addresses: [akka.tcp://WorkerSystem@127.0.0.1:54705]
[WARN] [SECURITY][04/02/2018 22:23:59.613] [ClusterSystem-akka.remote.default-remote-dispatcher-9] [akka.serialization.Serialization(akka://ClusterSystem)] Using the default Java serializer for class [worker.Cmd] which is not recommended because of performance implications. Use another serializer or disable this warning using the setting 'akka.actor.warn-about-java-serializer-usage'
[INFO] [04/02/2018 22:23:59.646] [ClusterSystem-akka.actor.default-dispatcher-20] [akka.cluster.Cluster(akka://ClusterSystem)] Cluster Node [akka.tcp://ClusterSystem@127.0.0.1:2551] - Received InitJoin message from [Actor[akka.tcp://ClusterSystem@127.0.0.1:2552/system/cluster/core/daemon/joinSeedNodeProcess-1#1585946061]] to [akka.tcp://ClusterSystem@127.0.0.1:2551]
[INFO] [04/02/2018 22:23:59.646] [ClusterSystem-akka.actor.default-dispatcher-20] [akka.cluster.Cluster(akka://ClusterSystem)] Cluster Node [akka.tcp://ClusterSystem@127.0.0.1:2551] - Sending InitJoinAck message from node [akka.tcp://ClusterSystem@127.0.0.1:2551] to [Actor[akka.tcp://ClusterSystem@127.0.0.1:2552/system/cluster/core/daemon/joinSeedNodeProcess-1#1585946061]]
[INFO] [04/02/2018 22:23:59.679] [ClusterSystem-akka.actor.default-dispatcher-2] [akka.cluster.Cluster(akka://ClusterSystem)] Cluster Node [akka.tcp://ClusterSystem@127.0.0.1:2551] - Node [akka.tcp://ClusterSystem@127.0.0.1:2552] is JOINING, roles [backend, dc-default]
[INFO] [04/02/2018 22:23:59.696] [WorkerSystem-akka.actor.default-dispatcher-7] [akka.tcp://WorkerSystem@127.0.0.1:54705/user/clusterClient] Connected to [akka.tcp://ClusterSystem@127.0.0.1:2551/system/receptionist]
[WARN] [SECURITY][04/02/2018 22:23:59.702] [WorkerSystem-akka.remote.default-remote-dispatcher-10] [akka.serialization.Serialization(akka://WorkerSystem)] Using the default Java serializer for class [worker.MasterWorkerProtocol$RegisterWorker] which is not recommended because of performance implications. Use another serializer or disable this warning using the setting 'akka.actor.warn-about-java-serializer-usage'
[INFO] [04/02/2018 22:23:59.714] [ClusterSystem-akka.actor.default-dispatcher-15] [akka://ClusterSystem/user/master/singleton] Worker registered: a6d14002-cd7e-4b68-b20a-22bed3dbb8fe
[INFO] [04/02/2018 22:23:59.794] [ClusterSystem-akka.actor.default-dispatcher-18] [akka.cluster.Cluster(akka://ClusterSystem)] Cluster Node [akka.tcp://ClusterSystem@127.0.0.1:2552] - Welcome from [akka.tcp://ClusterSystem@127.0.0.1:2551]
[INFO] [04/02/2018 22:24:00.012] [ClusterSystem-akka.actor.default-dispatcher-4] [akka.cluster.Cluster(akka://ClusterSystem)] Cluster Node [akka.tcp://ClusterSystem@127.0.0.1:2551] - Leader is moving node [akka.tcp://ClusterSystem@127.0.0.1:2552] to [Up]
[INFO] [04/02/2018 22:24:00.406] [ClusterSystem-akka.actor.default-dispatcher-6] [akka.tcp://ClusterSystem@127.0.0.1:2552/user/master] ClusterSingletonManager state change [Start -> Younger]
[ERROR] [04/02/2018 22:24:04.180] [ClusterSystem-akka.actor.default-dispatcher-18] [akka.actor.ActorSystemImpl(ClusterSystem)] bbb Lookup of shared journal at akka.tcp://ClusterSystem@127.0.0.1:2551/user/store timed out
akka.pattern.AskTimeoutException: Ask timed out on [ActorSelection[Anchor(akka://ClusterSystem/), Path(/user/store)]] after [10000 ms]. Sender[null] sent message of type "worker.Cmd".
	at akka.pattern.PromiseActorRef$$anonfun$1.apply$mcV$sp(AskSupport.scala:601)
	at akka.actor.Scheduler$$anon$4.run(Scheduler.scala:140)
	at scala.concurrent.Future$InternalCallbackExecutor$.unbatchedExecute(Future.scala:601)
	at scala.concurrent.BatchingExecutor$class.execute(BatchingExecutor.scala:109)
	at scala.concurrent.Future$InternalCallbackExecutor$.execute(Future.scala:599)
	at akka.actor.LightArrayRevolverScheduler$TaskHolder.executeTask(LightArrayRevolverScheduler.scala:328)
	at akka.actor.LightArrayRevolverScheduler$$anon$4.executeBucket$1(LightArrayRevolverScheduler.scala:279)
	at akka.actor.LightArrayRevolverScheduler$$anon$4.nextTick(LightArrayRevolverScheduler.scala:283)
	at akka.actor.LightArrayRevolverScheduler$$anon$4.run(LightArrayRevolverScheduler.scala:235)
	at java.lang.Thread.run(Thread.java:745)

[INFO] [04/02/2018 22:24:04.611] [main] [akka.remote.Remoting] Starting remoting
[INFO] [04/02/2018 22:24:04.670] [main] [akka.remote.Remoting] Remoting started; listening on addresses :[akka.tcp://ClusterSystem@127.0.0.1:54720]
[INFO] [04/02/2018 22:24:04.670] [main] [akka.remote.Remoting] Remoting now listens on addresses: [akka.tcp://ClusterSystem@127.0.0.1:54720]
[INFO] [04/02/2018 22:24:04.671] [main] [akka.cluster.Cluster(akka://ClusterSystem)] Cluster Node [akka.tcp://ClusterSystem@127.0.0.1:54720] - Starting up...
[WARN] [04/02/2018 22:24:04.675] [main] [akka.cluster.Cluster(akka://ClusterSystem)] Could not register Cluster JMX MBean with name=akka:type=Cluster as it is already registered. If you are running multiple clusters in the same JVM, set 'akka.cluster.jmx.multi-mbeans-in-same-jvm = on' in config
[INFO] [04/02/2018 22:24:04.675] [main] [akka.cluster.Cluster(akka://ClusterSystem)] Cluster Node [akka.tcp://ClusterSystem@127.0.0.1:54720] - Started up successfully
[WARN] [04/02/2018 22:24:04.679] [ClusterSystem-akka.actor.default-dispatcher-8] [akka.tcp://ClusterSystem@127.0.0.1:54720/system/cluster/core/daemon/downingProvider] Don't use auto-down feature of Akka Cluster in production. See 'Auto-downing (DO NOT USE)' section of Akka Cluster documentation.
[INFO] [04/02/2018 22:24:04.726] [ClusterSystem-akka.actor.default-dispatcher-20] [akka.cluster.Cluster(akka://ClusterSystem)] Cluster Node [akka.tcp://ClusterSystem@127.0.0.1:2551] - Received InitJoin message from [Actor[akka.tcp://ClusterSystem@127.0.0.1:54720/system/cluster/core/daemon/joinSeedNodeProcess-1#1871122618]] to [akka.tcp://ClusterSystem@127.0.0.1:2551]
[INFO] [04/02/2018 22:24:04.726] [ClusterSystem-akka.actor.default-dispatcher-20] [akka.cluster.Cluster(akka://ClusterSystem)] Cluster Node [akka.tcp://ClusterSystem@127.0.0.1:2551] - Sending InitJoinAck message from node [akka.tcp://ClusterSystem@127.0.0.1:2551] to [Actor[akka.tcp://ClusterSystem@127.0.0.1:54720/system/cluster/core/daemon/joinSeedNodeProcess-1#1871122618]]
[INFO] [04/02/2018 22:24:04.736] [ClusterSystem-akka.actor.default-dispatcher-18] [akka.cluster.Cluster(akka://ClusterSystem)] Cluster Node [akka.tcp://ClusterSystem@127.0.0.1:2551] - Node [akka.tcp://ClusterSystem@127.0.0.1:54720] is JOINING, roles [dc-default]
[INFO] [04/02/2018 22:24:04.742] [ClusterSystem-akka.actor.default-dispatcher-19] [akka.cluster.Cluster(akka://ClusterSystem)] Cluster Node [akka.tcp://ClusterSystem@127.0.0.1:54720] - Welcome from [akka.tcp://ClusterSystem@127.0.0.1:2551]
[INFO] [04/02/2018 22:24:04.759] [ClusterSystem-akka.actor.default-dispatcher-7] [akka.tcp://ClusterSystem@127.0.0.1:54720/user/frontend/masterProxy] Singleton identified at [akka.tcp://ClusterSystem@127.0.0.1:2551/user/master/singleton]
[INFO] [04/02/2018 22:24:06.017] [ClusterSystem-akka.actor.default-dispatcher-3] [akka.cluster.Cluster(akka://ClusterSystem)] Cluster Node [akka.tcp://ClusterSystem@127.0.0.1:2551] - Leader is moving node [akka.tcp://ClusterSystem@127.0.0.1:54720] to [Up]

Any suggestion here... will benefit in understanding.

**Comment by anant1525** [comment]
Hi @ktoso 

I have debugged and what i got is my FrontEnd Actor tried to send work to Master using masterproxy but Work didn't reached Master. So no Ack received leading to Ask time out 

not sure what is going wrong, master proxy or don't know

 	ActorRef masterProxy =
			getContext().actorOf(ClusterSingletonProxy.props("/user/master/active",
			  ClusterSingletonProxySettings.create(getContext().system()).withRole("backend")), "masterProxy");

**Comment by anant1525** [comment]
Hi,

It took time but sorted the error. problem was 2.3 --> 2.5 explicitly mentioning the singleton name,
i mentioned the name which we were using as sample below, and code is working like a charm.


      ClusterSingletonProxy.props(
          "/user/master",
          ClusterSingletonProxySettings.create(getContext().system()).withRole("backend").withSingletonName("singleton")),
      "masterProxy");
